mutation ($id: UUID!, $user_id: UUID!, $publication_id: UUID!, $share: Float!, $order: Int!){
  result: publicationAuthorInsert(author: {id: $id, publicationId: $publication_id, userId: $user_id, share: $share, order: $order}) {
    id
    msg
    result: author{
      ...Author
    }
  }
}

fragment Author on PublicationAuthorGQLModel {
  __typename
  id
  lastchange
  publication { id name }
  order
  share
  user { id }
}